# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno
# push:
#  branches: ["main"]

name: Deno

on:
  workflow_dispatch:
  repository_dispatch:
    types: [schedule-run]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '30 4 * * 2'
  
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      #- name: Setup Deno
        # uses: denoland/setup-deno@v1
        #uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        #with:
        #  deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Install deno
        uses: denolib/setup-deno@master

      - name: Run deno
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --local user.email "xchuan@gmail.com"
          git config --local user.name "Chuan"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git pull
          deno run --unstable --allow-net --allow-read --allow-write --import-map=import_map.json mod.ts
          git add .
          git commit -m "update by github action"
          git push
